language: python
python:
  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
addons:
  postgresql: "9.4"
services:
  - postgresql
install: "pip install -r requirements.txt"
before_script:
  - psql -f sql/create_user_and_database.sql -U postgres
  - psql -d openods -f sql/run_migration_scripts.sql
  - psql -d openods -f sql/import_test_data.sql
env:
- API_USER=env_test_user API_PASS=env_test_pass CACHE_TIMEOUT=10 APP_HOSTNAME=localhost:5000 API_USE_AUTH=TRUE
script: nosetests
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/17a13f110367e79b54b9
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always