version: '3'

services:
  web:
    container_name: openods-web
    build:
      context: .
      dockerfile: Dockerfile-openods
    ports:
      - "8000:8080"
    links:
      - "db:database"
    depends_on:
      - db
  db:
    container_name: openods-postgres
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5433:5432"
